import "package:flutter/material.dart";

/// The app's colour schemes, generated by Material Theme Builder.
///
/// Trimmed to the two [MaterialApp] actually asks for. The generator also
/// emits medium- and high-contrast variants of each, plus an `extendedColors`
/// hook and the `ExtendedColor` / `ColorFamily` types that serve it. Nothing
/// read any of them, and no setting in this app reaches them — regenerate from
/// Theme Builder if contrast variants are ever wanted.
class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF4A672D),
      surfaceTint: Color(0xFF4A672D),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFCBEEA5),
      onPrimaryContainer: Color(0xFF0E2000),
      secondary: Color(0xFF57624A),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFDBE7C8),
      onSecondaryContainer: Color(0xFF151E0B),
      tertiary: Color(0xFF386664),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFBBECE8),
      onTertiaryContainer: Color(0xFF00201F),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFF9FAEF),
      onSurface: Color(0xFF1A1C16),
      onSurfaceVariant: Color(0xFF44483D),
      outline: Color(0xFF74796C),
      outlineVariant: Color(0xFFC4C8BA),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF2F312A),
      inversePrimary: Color(0xFFB0D18B),
      primaryFixed: Color(0xFFCBEEA5),
      onPrimaryFixed: Color(0xFF0E2000),
      primaryFixedDim: Color(0xFFB0D18B),
      onPrimaryFixedVariant: Color(0xFF334E17),
      secondaryFixed: Color(0xFFDBE7C8),
      onSecondaryFixed: Color(0xFF151E0B),
      secondaryFixedDim: Color(0xFFBFCBAD),
      onSecondaryFixedVariant: Color(0xFF404A34),
      tertiaryFixed: Color(0xFFBBECE8),
      onTertiaryFixed: Color(0xFF00201F),
      tertiaryFixedDim: Color(0xFFA0CFCC),
      onTertiaryFixedVariant: Color(0xFF1F4E4C),
      surfaceDim: Color(0xFFD9DBD0),
      surfaceBright: Color(0xFFF9FAEF),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF3F5E9),
      surfaceContainer: Color(0xFFEDEFE4),
      surfaceContainerHigh: Color(0xFFE8E9DE),
      surfaceContainerHighest: Color(0xFFE2E3D8),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFB0D18B),
      surfaceTint: Color(0xFFB0D18B),
      onPrimary: Color(0xFF1E3702),
      primaryContainer: Color(0xFF334E17),
      onPrimaryContainer: Color(0xFFCBEEA5),
      secondary: Color(0xFFBFCBAD),
      onSecondary: Color(0xFF2A331F),
      secondaryContainer: Color(0xFF404A34),
      onSecondaryContainer: Color(0xFFDBE7C8),
      tertiary: Color(0xFFA0CFCC),
      onTertiary: Color(0xFF003735),
      tertiaryContainer: Color(0xFF1F4E4C),
      onTertiaryContainer: Color(0xFFBBECE8),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF12140E),
      onSurface: Color(0xFFE2E3D8),
      onSurfaceVariant: Color(0xFFC4C8BA),
      outline: Color(0xFF8E9285),
      outlineVariant: Color(0xFF44483D),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE2E3D8),
      inversePrimary: Color(0xFF4A672D),
      primaryFixed: Color(0xFFCBEEA5),
      onPrimaryFixed: Color(0xFF0E2000),
      primaryFixedDim: Color(0xFFB0D18B),
      onPrimaryFixedVariant: Color(0xFF334E17),
      secondaryFixed: Color(0xFFDBE7C8),
      onSecondaryFixed: Color(0xFF151E0B),
      secondaryFixedDim: Color(0xFFBFCBAD),
      onSecondaryFixedVariant: Color(0xFF404A34),
      tertiaryFixed: Color(0xFFBBECE8),
      onTertiaryFixed: Color(0xFF00201F),
      tertiaryFixedDim: Color(0xFFA0CFCC),
      onTertiaryFixedVariant: Color(0xFF1F4E4C),
      surfaceDim: Color(0xFF12140E),
      surfaceBright: Color(0xFF373A33),
      surfaceContainerLowest: Color(0xFF0C0F09),
      surfaceContainerLow: Color(0xFF1A1C16),
      surfaceContainer: Color(0xFF1E211A),
      surfaceContainerHigh: Color(0xFF282B24),
      surfaceContainerHighest: Color(0xFF33362E),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        textTheme: textTheme.apply(
          bodyColor: colorScheme.onSurface,
          displayColor: colorScheme.onSurface,
        ),
        // `colorScheme.background` was deprecated in Flutter 3.22 and is just
        // `surface` now; naming it kept the analyzer complaining and said
        // nothing the default did not already do.
        scaffoldBackgroundColor: colorScheme.surface,
        canvasColor: colorScheme.surface,
        // Every card in the app asks for `elevation: 0`, and Material 3's
        // default card colour is `surfaceContainerLow` — one step from the
        // scaffold. Cards and background came out near-identical, which is why
        // the pages read as one flat sheet. Two steps up separates them
        // without reaching for a shadow.
        cardTheme: CardThemeData(
          elevation: 0,
          color: colorScheme.surfaceContainer,
          margin: EdgeInsets.zero,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
        snackBarTheme: SnackBarThemeData(
          behavior: SnackBarBehavior.floating,
          backgroundColor: colorScheme.inverseSurface,
          contentTextStyle: TextStyle(color: colorScheme.onInverseSurface),
        ),
      );
}
