import "package:flutter/material.dart";

/// The app's colour schemes, generated by Material Theme Builder.
///
/// Trimmed to the two [MaterialApp] actually asks for. The generator also
/// emits medium- and high-contrast variants of each, plus an `extendedColors`
/// hook and the `ExtendedColor` / `ColorFamily` types that serve it. Nothing
/// read any of them, and no setting in this app reaches them — regenerate from
/// Theme Builder if contrast variants are ever wanted.
class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(4283066157),
      surfaceTint: Color(4283066157),
      onPrimary: Color(4294967295),
      primaryContainer: Color(4291554981),
      onPrimaryContainer: Color(4279115776),
      secondary: Color(4283916874),
      onSecondary: Color(4294967295),
      secondaryContainer: Color(4292601800),
      onSecondaryContainer: Color(4279574027),
      tertiary: Color(4281886308),
      onTertiary: Color(4294967295),
      tertiaryContainer: Color(4290505960),
      onTertiaryContainer: Color(4278198303),
      error: Color(4290386458),
      onError: Color(4294967295),
      errorContainer: Color(4294957782),
      onErrorContainer: Color(4282449922),
      surface: Color(4294572783),
      onSurface: Color(4279901206),
      onSurfaceVariant: Color(4282665021),
      outline: Color(4285823340),
      outlineVariant: Color(4291086522),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4281282858),
      inversePrimary: Color(4289778059),
      primaryFixed: Color(4291554981),
      onPrimaryFixed: Color(4279115776),
      primaryFixedDim: Color(4289778059),
      onPrimaryFixedVariant: Color(4281552407),
      secondaryFixed: Color(4292601800),
      onSecondaryFixed: Color(4279574027),
      secondaryFixedDim: Color(4290759597),
      onSecondaryFixedVariant: Color(4282403380),
      tertiaryFixed: Color(4290505960),
      onTertiaryFixed: Color(4278198303),
      tertiaryFixedDim: Color(4288729036),
      onTertiaryFixedVariant: Color(4280241740),
      surfaceDim: Color(4292467664),
      surfaceBright: Color(4294572783),
      surfaceContainerLowest: Color(4294967295),
      surfaceContainerLow: Color(4294178281),
      surfaceContainer: Color(4293783524),
      surfaceContainerHigh: Color(4293454302),
      surfaceContainerHighest: Color(4293059544),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(4289778059),
      surfaceTint: Color(4289778059),
      onPrimary: Color(4280170242),
      primaryContainer: Color(4281552407),
      onPrimaryContainer: Color(4291554981),
      secondary: Color(4290759597),
      onSecondary: Color(4280955679),
      secondaryContainer: Color(4282403380),
      onSecondaryContainer: Color(4292601800),
      tertiary: Color(4288729036),
      onTertiary: Color(4278204213),
      tertiaryContainer: Color(4280241740),
      onTertiaryContainer: Color(4290505960),
      error: Color(4294948011),
      onError: Color(4285071365),
      errorContainer: Color(4287823882),
      onErrorContainer: Color(4294957782),
      surface: Color(4279374862),
      onSurface: Color(4293059544),
      onSurfaceVariant: Color(4291086522),
      outline: Color(4287533701),
      outlineVariant: Color(4282665021),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4293059544),
      inversePrimary: Color(4283066157),
      primaryFixed: Color(4291554981),
      onPrimaryFixed: Color(4279115776),
      primaryFixedDim: Color(4289778059),
      onPrimaryFixedVariant: Color(4281552407),
      secondaryFixed: Color(4292601800),
      onSecondaryFixed: Color(4279574027),
      secondaryFixedDim: Color(4290759597),
      onSecondaryFixedVariant: Color(4282403380),
      tertiaryFixed: Color(4290505960),
      onTertiaryFixed: Color(4278198303),
      tertiaryFixedDim: Color(4288729036),
      onTertiaryFixedVariant: Color(4280241740),
      surfaceDim: Color(4279374862),
      surfaceBright: Color(4281809459),
      surfaceContainerLowest: Color(4278980361),
      surfaceContainerLow: Color(4279901206),
      surfaceContainer: Color(4280164634),
      surfaceContainerHigh: Color(4280822564),
      surfaceContainerHighest: Color(4281546286),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
     useMaterial3: true,
     brightness: colorScheme.brightness,
     colorScheme: colorScheme,
     textTheme: textTheme.apply(
       bodyColor: colorScheme.onSurface,
       displayColor: colorScheme.onSurface,
     ),
     scaffoldBackgroundColor: colorScheme.background,
     canvasColor: colorScheme.surface,
  );
}
