// A stand-in for lib/firebase_options.dart, for machines that do not have one.
//
// The real file is generated by the FlutterFire CLI and is gitignored, because
// it carries the Web API key — see the note beside it in .gitignore. That was
// fine while nothing imported it outside `main()`, and stopped being fine when
// lib/database/session_apps.dart started opening a second FirebaseApp with
// `DefaultFirebaseOptions.currentPlatform`: from then on the analyzer could not
// resolve lib/ at all without it, so `flutter analyze` failed on a fresh clone
// and `flutter test` never ran. Every CI run from 2026-09-03 to 2026-09-09 was
// red for this and nothing else.
//
// So CI copies this file into place instead. The values are deliberately not
// the project's: nothing in a test or an analysis pass opens a socket, and a
// stub that happened to work against the real project would be a stub that
// could do damage if something ever did. If you are reading this in a stack
// trace, something tried to reach Firebase in a context that has no Firebase.
//
// Keep the shape in step with the generated file. It is only the class and the
// getter that lib/ depends on; the fields exist because FirebaseOptions
// requires them.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'not-a-key-ci-stub',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'ci-stub',
    authDomain: 'ci-stub.firebaseapp.com',
    databaseURL: 'https://ci-stub-default-rtdb.firebaseio.com',
    storageBucket: 'ci-stub.appspot.com',
    measurementId: 'G-0000000000',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'not-a-key-ci-stub',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'ci-stub',
    databaseURL: 'https://ci-stub-default-rtdb.firebaseio.com',
    storageBucket: 'ci-stub.appspot.com',
  );
}
